@employeeManagement_HostAddress = https://localhost:7105

### DELETE employee (success)
DELETE {{employeeManagement_HostAddress}}/api/employees/Delete1
Accept: application/json
###

### DELETE employee (not found)
DELETE {{employeeManagement_HostAddress}}/api/employees/Delete0
Accept: application/json
###
