@employeeManagement_HostAddress = https://localhost:7105

### DELETE employee (success)
DELETE {{employeeManagement_HostAddress}}/api/employee/Delete/1
Accept: application/json
###

### DELETE employee (not found)
DELETE {{employeeManagement_HostAddress}}/api/employee/Delete/0
Accept: application/json
###
