@employeeManagement_HostAddress = https://localhost:7105

### PUT update employee (success)
PUT {{employeeManagement_HostAddress}}/api/Employee/Update/1
Content-type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": 60000
}
###

### PUT update employee (not found)
PUT {{employeeManagement_HostAddress}}/api/Employee/Update/0
Content-type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": 60000
}
###

### PUT update employee (invalid salary)
PUT {{employeeManagement_HostAddress}}/api/Employee/Update/1
Content-type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": -100
}
###
