@employeeManagement_HostAddress = https://localhost:7105

/// GET /api/employees
/// Should return 200 OK with all employees
GET {{employeeManagement_HostAddress}}/api/employees
Accept: application/json
###

/// Successful GET /api/employees/{id}
/// Should return 200 OK with the employee if found
GET {{employeeManagement_HostAddress}}/api/employees/1
Accept: application/json
###

/// Failed GET /api/employees/{id} (id not found)
/// Should return 404 Not Found
GET {{employeeManagement_HostAddress}}/api/employees/0
Accept: application/json
###

/// Successful POST /api/employees
/// Should return 201 Created with the new employee
POST {{employeeManagement_HostAddress}}/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": 50000
}
###

/// Failed POST /api/employees (name field is missing)
/// Should return 400 Bad Request (validation error)
POST {{employeeManagement_HostAddress}}/api/employees
Content-Type: application/json
Accept: application/json

{
  "position": "Developer",
  "department": "DevOps",
  "salary": 50000
}
###

/// Failed POST /api/employees (name field is null)
/// Should return 400 Bad Request (validation error)
POST {{employeeManagement_HostAddress}}/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": null,
  "position": "Developer",
  "department": "DevOps",
  "salary": 50000
}
###

/// Failed POST /api/employees (salary is out of range)
/// Should return 400 Bad Request (validation error)
POST {{employeeManagement_HostAddress}}/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": -100
}
###

/// Successful PUT /api/employees/{id}
/// Should return 200 OK with the updated employee
PUT {{employeeManagement_HostAddress}}/api/employees/1
Content-type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": 60000
}
###

/// Failed PUT /api/employees/{id} (id not found)
/// Should return 404 Not Found
PUT {{employeeManagement_HostAddress}}/api/employees/0
Content-type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": 60000
}
###

/// Failed PUT /api/employees/{id} (salary out of range)
/// Should return 400 Bad Request (validation error)
PUT {{employeeManagement_HostAddress}}/api/employees/1
Content-type: application/json
Accept: application/json

{
  "name": "Nick Ant",
  "position": "Developer",
  "department": "DevOps",
  "salary": -100
}
###

/// Successful DELETE /api/employees/{id}
// Should return 200 OK or 204 No Content
DELETE {{employeeManagement_HostAddress}}/api/employees/1
Accept: application/json
###

/// Failed DELETE /api/employees/{id} (id not found)
/// Should return 404 Not Found
DELETE {{employeeManagement_HostAddress}}/api/employees/0
Accept: application/json
###
